apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdb
  labels:
    app: appdb
spec:
  selector:
    matchLabels:
      app: appdb
  replicas: 2
  template:
    metadata:
      labels:
        app: appdb
    spec:
      initcontainers:
        - name: busybox
          image: busybox:1.28
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: appdb-vol
      containers:
        - name: appdb
          image: vprofile/vprofiledb:V1
          ports:
            - name: appdb-port
              containerPort: 3306
          volumeMounts:
             - mountPath: /var/lib/mysql
               name: appdb-vol
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      volumes:
        - name: appdb-vol
          persistentVolumeClaim:
            claimName: vol-k8s-pvc
      nodeSelector:
          task: testing
